name: Deploy Mini-DPS

on:
  push:
    branches: [main]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy backend to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/mini-dps
            git pull origin main

            cd apps/api
            docker build -t mini-dps-api .

            docker stop mini-dps-api || true
            docker rm mini-dps-api || true

            docker run -d \
              --name mini-dps-api \
              --env-file .env \
              -p 80:3001 \
              mini-dps-api

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install frontend
        working-directory: apps/web
        run: npm ci

      - name: Build frontend
        working-directory: apps/web
        env:
          NEXT_PUBLIC_API_URL: http://13.60.17.29
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy frontend to S3
        working-directory: apps/web
        run: aws s3 sync out/ s3://mini-dps-frontend-elijah --delete